# Generated by Django 6.1 on 2026-08-16 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('financial', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='accounts.advisorprofile')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions_criadas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='organizations.organization')),
            ],
            options={
                'ordering': ['-ano_referencia', '-mes_referencia'],
                'constraints': [models.UniqueConstraint(fields=('advisor', 'mes_referencia', 'ano_referencia'), name='uma_comissao_por_assessor_por_mes'), models.CheckConstraint(condition=models.Q(('mes_referencia__gte', 1), ('mes_referencia__lte', 12)), name='mes_referencia_valido')],
            },
        ),
    ]
