# Generated by Django 6.1 on 2026-08-16 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('financial', '0002_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PJ2PrevidenciaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('data_lancamento', models.DateField(help_text='Data original do registro na origem (planilha ou lançamento manual).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('classificacao', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('nivel_1', models.CharField(blank=True, max_length=255)),
                ('nivel_2', models.CharField(blank=True, max_length=255)),
                ('nivel_3', models.CharField(blank=True, max_length=255)),
                ('nivel_4', models.CharField(blank=True, max_length=255)),
                ('codigo_cliente', models.CharField(max_length=100)),
                ('codigo_assessor', models.CharField(max_length=50)),
                ('receita_bruta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receita_liquida', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comissao_percentual_escritorio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comissao_escritorio', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PJ2SegurosEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('data_lancamento', models.DateField(help_text='Data original do registro na origem (planilha ou lançamento manual).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('seguradora', models.CharField(choices=[('PRUDENTIAL', 'Prudential'), ('METLIFE', 'MetLife'), ('ICATU', 'Icatu')], max_length=20)),
                ('cliente', models.CharField(max_length=255)),
                ('comissao_bruta_escritorio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('comissao_assessor_60', models.DecimalField(decimal_places=2, help_text='Campo "Comissão Assessor 60%" da origem — valor já líquido informado manualmente, não recalculado pelo sistema (suposição registrada na análise arquitetural).', max_digits=14)),
                ('parcela', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('data_lancamento', models.DateField(help_text='Data original do registro na origem (planilha ou lançamento manual).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('parceiro', models.CharField(choices=[('VIPMARES', 'Vipmares'), ('MD_GARANTIDOR', 'MD Garantidor'), ('LMS_FOCUS', 'LMS/Focus'), ('RODOBENS', 'Rodobens'), ('DUOPLAN', 'Duoplan'), ('ESOLEN_FINEPE', 'Esolen (Finepe)'), ('PRIMO_PRECATORIOS', 'Primo Precatórios'), ('NEWAVE', 'Newave'), ('FINANC_SAFRA', 'Financ Safra'), ('ESSENCIAL', 'Essencial'), ('REAL_CRED', 'Real Cred'), ('PREV', 'Prev'), ('SORIA_CAPITAL', 'Soria Capital'), ('BV_FINANCEIRA', 'BV Financeira')], max_length=30)),
                ('cliente', models.CharField(blank=True, max_length=255)),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('percentual_imposto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_imposto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PJ1Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('data_lancamento', models.DateField(help_text='Data original do registro na origem (planilha ou lançamento manual).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(max_length=255)),
                ('produto', models.CharField(max_length=255)),
                ('nivel_1', models.CharField(blank=True, max_length=255)),
                ('nivel_2', models.CharField(blank=True, max_length=255)),
                ('nivel_3', models.CharField(blank=True, max_length=255)),
                ('codigo_cliente', models.CharField(max_length=100)),
                ('receita', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receita_liquida', models.DecimalField(decimal_places=2, max_digits=14)),
                ('repasse_percentual_escritorio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comissao_bruta_escritorio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('codigo_assessor_direto', models.CharField(max_length=50)),
                ('repasse_percentual_assessor_direto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comissao_assessor_direto', models.DecimalField(decimal_places=2, help_text='Snapshot: valor já calculado no momento da importação. Não é recalculado a partir de Commission depois.', max_digits=14)),
                ('advisor', models.ForeignKey(blank=True, help_text='Nulo quando o assessor não pôde ser identificado na importação (linha fica como pendente de revisão).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='accounts.advisorprofile')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
