# Generated by Django 6.1 on 2026-08-16 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('financial', '0003_pj2previdenciaentry_pj2segurosentry_plusentry_and_more'),
        ('imports', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pj1entry',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='pj1entry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='pj2previdenciaentry',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Nulo quando o assessor não pôde ser identificado na importação (linha fica como pendente de revisão).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='accounts.advisorprofile'),
        ),
        migrations.AddField(
            model_name='pj2previdenciaentry',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pj2previdenciaentry',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='pj2previdenciaentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='pj2segurosentry',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Nulo quando o assessor não pôde ser identificado na importação (linha fica como pendente de revisão).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='accounts.advisorprofile'),
        ),
        migrations.AddField(
            model_name='pj2segurosentry',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pj2segurosentry',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='pj2segurosentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='pj2segurosentry',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pj2seguros_entries', to='financial.product'),
        ),
        migrations.AddField(
            model_name='plusentry',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Nulo quando o assessor não pôde ser identificado na importação (linha fica como pendente de revisão).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='accounts.advisorprofile'),
        ),
        migrations.AddField(
            model_name='plusentry',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plusentry',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='plusentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_entries', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='plusentry',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plus_entries', to='financial.product'),
        ),
        migrations.AddConstraint(
            model_name='pj1entry',
            constraint=models.CheckConstraint(condition=models.Q(('mes_referencia__gte', 1), ('mes_referencia__lte', 12)), name='financial_pj1entry_mes_referencia_valido'),
        ),
        migrations.AddConstraint(
            model_name='pj1entry',
            constraint=models.UniqueConstraint(fields=('organization', 'codigo_assessor_direto', 'codigo_cliente', 'data_lancamento', 'comissao_bruta_escritorio'), name='pj1entry_chave_composta_duplicidade'),
        ),
        migrations.AddConstraint(
            model_name='pj2previdenciaentry',
            constraint=models.CheckConstraint(condition=models.Q(('mes_referencia__gte', 1), ('mes_referencia__lte', 12)), name='financial_pj2previdenciaentry_mes_referencia_valido'),
        ),
        migrations.AddConstraint(
            model_name='pj2previdenciaentry',
            constraint=models.UniqueConstraint(fields=('organization', 'codigo_assessor', 'codigo_cliente', 'data_lancamento', 'comissao_escritorio'), name='pj2preventry_chave_composta_duplicidade'),
        ),
        migrations.AddConstraint(
            model_name='pj2segurosentry',
            constraint=models.CheckConstraint(condition=models.Q(('mes_referencia__gte', 1), ('mes_referencia__lte', 12)), name='financial_pj2segurosentry_mes_referencia_valido'),
        ),
        migrations.AddConstraint(
            model_name='plusentry',
            constraint=models.CheckConstraint(condition=models.Q(('mes_referencia__gte', 1), ('mes_referencia__lte', 12)), name='financial_plusentry_mes_referencia_valido'),
        ),
    ]
